version: '3.1'
services:
  ftspa:
    image: frontendcompose_ftspa
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M	
    ports:
     - "3004:3004"

  ftpayment:
    image: frontendcompose_ftpayment
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M	
    ports:
     - "3001:3001"

  ftadvert:
    image: frontendcompose_ftadvert
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M	
    ports:
     - "3002:3002"

  ftactivity:
    image: frontendcompose_ftactivity
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M	
    ports:
     - "3003:3003"
 
  ftnginx:
    image: frontendcompose_ftnginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M	
    ports:
     - "3000:3000"	 